In [9]:
# Numpyのテスト
import numpy as np
print(np.version.full_version)

1.12.1


In [10]:
# 配列の生成
# 標準の配列と競合しないように，import文は上記のように記述する．
a = np.array([0,1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5]
1
(6,)


In [11]:
# 配列を2次元の行列に変換
b = a.reshape((3,2))
print(b)
print(b.ndim)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]]
2
(3, 2)


In [12]:
# 通常の代入ではコピーは行われない．
# 浅いコピーと深いコピー(?) 
# bを操作しているつもりでも，(参照なので)aも変わってしまう．
b[1][0]=77
print(a)
# 実際にコピーが必要な場合にはcopy()を用いる．
c = a.reshape((3,2)).copy()
print(c)
c[0][0] = -99
# 要素の値が変わっていることに注目
print(a)
print(c)

[ 0  1 77  3  4  5]
[[ 0  1]
 [77  3]
 [ 4  5]]
[ 0  1 77  3  4  5]
[[-99   1]
 [ 77   3]
 [  4   5]]


In [13]:
# numpyは要素ごとの演算が容易
# a = np.array([0,1,2,3,4,5])
print(a*2)
print(a**2)
# (参考)通常のPython標準の配列
print([0,1,2,3,4,5]*2)
print([0,1,2,3,4,5]**2)

[  0   2 154   6   8  10]
[   0    1 5929    9   16   25]
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [14]:
# 配列への要素アクセス．インデックス用の配列を用いて操作できる．
a[np.array([2,3,4])]

array([77,  3,  4])

In [20]:
# 条件を満たす要素だけを取り出すことも容易
a>4

array([False, False,  True, False, False,  True], dtype=bool)

In [21]:
a[a>4]

array([77,  5])

In [25]:
# 条件外の要素を一定値に揃える例
a[a>4] = 4
a

array([0, 1, 4, 3, 4, 4])

In [26]:
# 上下限を設定する方法としてはclip()がある
a.clip(0,4)

array([0, 1, 4, 3, 4, 4])

In [27]:
# 不適切な値の除去の例
c = np.array([1,2, np.NAN, 3,4])
c

array([  1.,   2.,  nan,   3.,   4.])

In [28]:
np.isnan(c)

array([False, False,  True, False, False], dtype=bool)

In [29]:
c[~np.isnan(c)]

array([ 1.,  2.,  3.,  4.])

In [30]:
np.mean(c[~np.isnan(c)])

2.5