In [1]:
# Numpyのテスト
import numpy as np
print(np.version.full_version)

1.12.1


In [11]:
# 配列の生成
# 標準の配列と競合しないように，import文は上記のように記述する．
a = np.array([0,1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5]
1
(6,)


In [12]:
# 配列を2次元の行列に変換
b = a.reshape((3,2))
print(b)
print(b.ndim)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]]
2
(3, 2)


In [13]:
# 通常の代入ではコピーは行われない．
# 浅いコピーと深いコピー(?) 
# bを操作しているつもりでも，(参照なので)aも変わってしまう．
b[1][0]=77
print(a)
# 実際にコピーが必要な場合にはcopy()を用いる．
c = a.reshape((3,2)).copy()
print(c)
c[0][0] = -99
# 要素の値が変わっていることに注目
print(a)
print(c)

[ 0  1 77  3  4  5]
[[ 0  1]
 [77  3]
 [ 4  5]]
[ 0  1 77  3  4  5]
[[-99   1]
 [ 77   3]
 [  4   5]]


In [19]:
# 要素ごとのnumpyは得意
a = np.array([0,1,2,3,4,5])
print(a*2)
print(a**2)
# (参考)通常のPython標準の配列
print([0,1,2,3,4,5]*2)
print([0,1,2,3,4,5]**2)

[ 0  2  4  6  8 10]
[ 0  1  4  9 16 25]
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'